### ISSUE TITLE
Support for ARM64-based CPUs

### ISSUE THREAD

**Issue by phillytan** [DopplerHQ/kubernetes-operator#14]
Hey Doppler Team!

Our team is planning to explore using this Kubernetes operator on ARM64-based Devices (AWS Graviton2 + Raspberry Pi). Is it possible to provide support for this architecture?

Looking into your GitHub Actions Script, it looks like this can be done with a one-liner. Within this [job](https://github.com/DopplerHQ/kubernetes-operator/blob/main/.github/workflows/release.yml#L29-L38), you can enter in `platforms: linux/amd64,linux/arm64` after line 32 to easily provide support. You can refer to [this document](https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md) for more information.

Only caveat with this approach is builds will take longer due to ARM64 Emulation. From my testing it took roughly 40 minutes to build the Docker Container on a self-hosted GitHub Actions Runner.

Hoping for your team's support for this though!

**Comment by Goran-n** [comment]
This would be ideal as the Doppler Operator is currently unusable on Graviton based instances

**Comment by nmanoogian** [comment]
Thanks everyone! Sorry it's taken some time to get back to you on this.

This is absolutely on our radar and we're planning to pick this up in the next few weeks.

**Comment by nmanoogian** [comment]
Thanks again to @phillytan for laying out the work to be done and thanks to everyone who chimed in on this issue!

doppler-kubernetes-operator v1.1.1 has just been released with both ARM and AMD architectures! Feel free to kick the tires and let me know if you run into problems.
