### ISSUE TITLE
Feature: Support kubernetes.io/tls instead of only Opaque

### ISSUE THREAD

**Issue by a-nldisr** [DopplerHQ/kubernetes-operator#25]
As I understand from the Kubernetes documentation the kubernetes.io/tls only difference is enforcing DER standards and that the key/cert is present. So consider this as a nice-to-have feature request.

Current code only supports Opaque Kubernetes secrets.
https://github.com/DopplerHQ/kubernetes-operator/blob/98ce8ccbefada12a4fa2ebff778f311059cbec5a/controllers/dopplersecret_controller_secrets.go#L196
Having the operator create kubernetes.io/tls when a certificate is present would be nice!

**Comment by nmanoogian** [comment]
Thanks for recommending this, @a-nldisr! I'll pass this along to our product team and let you know if we have any follow-up questions or info.

**Comment by a-nldisr** [comment]
Want to extend this feature request with other types:
https://kubernetes.io/docs/concepts/configuration/secret/#secret-types

**Comment by nmanoogian** [comment]
Thanks @a-nldisr 👍

**Comment by bjd2385** [comment]
I'll second this, I want to be able to generate other secret types (particularly type `kubernetes.io/tls`) as well. Kind of makes this unusable for me, unfortunately.

https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
https://github.com/DopplerHQ/kubernetes-operator/tree/caeb2c262685f37bf7f5e3013eba70a4b1724d6d#name-transformers

**Comment by bjd2385** [comment]
While trying to create a PR to implement this feature, it looks like all the operator does as far as key string mangling is make an API call and the transforms are built into the API ~

https://docs.doppler.com/docs/accessing-secrets#name-transformers

Really unfortunate that a product update on that end needs to be made for something as simple as manipulating a string. And if it's available in the API anyway as additional processing, why can't we just create any secret name we want (not just all uppercase)? Wouldn't that simplify this problem drastically, and probably reduce cost?

**Comment by watsonian** [comment]
Support for this was added in https://github.com/DopplerHQ/kubernetes-operator/pull/47. You can read more about it in [the docs](https://github.com/DopplerHQ/kubernetes-operator/blob/main/docs/custom_types_and_processors.md).
