### ISSUE TITLE
Request for change of behavior introduced in 1.2.0 which breaks prior use cases

### ISSUE THREAD

**Issue by dkowsley** [DopplerHQ/kubernetes-operator#28]
In https://github.com/DopplerHQ/kubernetes-operator/commit/c55ad5e5e98a4fc459825ac49b57125be681d839, a change was introduced which only allows DopplerSecret objects in the operator namespace. This breaks self-service within multi-tenancy. 

Instead, I would like to propose a change that takes into account existing RBAC in the cluster while providing the original flexibility. 

1. Add a ValidatingWebhookConfiguration that registers a webhook for all DopplerSecret objects.
2. Reject any DopplerSecret objects that attempt to overwrite any existing managedSecrets
3. Reject any Doppler Secret objects that violate the user's RBAC. Combining [SelfSubjectAccessReview](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#request:~:text=operation%3A%20UPDATE-,userInfo,-%3A) and [impersonation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation) with the [userInfo](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#request:~:text=operation%3A%20UPDATE-,userInfo,-%3A) data will allow the operator to determine authorization of the action at time of creation of the DopplerSecret

## For those looking for a solution to maintain the previous behavior

```You should be able to specify the previous chart version of 1.1.1 with helm. That is our temporary solution.```

**Comment by dkowsley** [comment]
Here are the two flows that this contains:

### User does NOT have RBAC access to source/dest secrets
```mermaid
sequenceDiagram
User ->> k8s: PUT/PATCH/POST DopplerSecret
k8s ->> Operator: ValidatingWebhook POST payload (contains userInfo from User)
Operator ->>k8s: SelfSubjectAccessReview (with payload.userInfo impersonation)
k8s -x Operator: NO either source and/or dest secrets are not manageable by User
Operator -x k8s: Resource is not valid. Deny it.
k8s -x User: DopplerSecret rejected.
```

### User has RBAC access to source/dest secrets
```mermaid
sequenceDiagram
User ->> k8s: PUT/PATCH/POST DopplerSecret
k8s ->> Operator: ValidatingWebhook POST payload (contains userInfo from User)
Operator ->> k8s: SelfSubjectAccessReview (with payload.userInfo impersonation)
k8s ->> Operator: YES source/dest secrets are managemable by User.
Operator ->> k8s: Resource is valid. Accept it.
k8s ->> User: DopplerSecret accepted
Operator --> k8s: Sees new DopplerSecret
Operator ->> Doppler API: Grabs config with token
Operator ->> k8s: PUT/PATCH/POST config to managedSecret
```

**Comment by draganm** [comment]
+1 
I've stumbled over this issue too. Using ArgoCD to deploy applications in different namespaces. It would be great if I could keep `DopplerSecret` resources together with the rest of the application resources so that they would be removed when the namespace is removed.

**Comment by adambozson** [comment]
+1 This change wasn't documented so we've had downtime while trying to work out what the issue is. We rolled back to v1.1.1 for the time being.

**Comment by draganm** [comment]
are there any plans for a new release of the operator without restriction of the namespace?

**Comment by nmanoogian** [comment]
Thanks for all of the feedback! We're reviewing options internally for how to meet these use cases. I'll post here with any updates.
