### ISSUE TITLE
recommended.yaml not available in latest

### ISSUE THREAD

**Issue by pve** [DopplerHQ/kubernetes-operator#33]
https://github.com/DopplerHQ/kubernetes-operator/releases/latest/download/recommended.yaml
used to work, we have this in a Kustomize file.
This stopped working, as it redirects to https://github.com/DopplerHQ/kubernetes-operator/releases/download/v1.2.2/recommended.yaml

1.2.1 is also MIA
1.2.0 seems to still work.

**Comment by pve** [comment]
This is mentioned in 
https://github.com/DopplerHQ/kubernetes-operator/#readme

but it does not work:

kubectl apply -f https://github.com/DopplerHQ/kubernetes-operator/releases/latest/download/recommended.yaml
error: unable to read URL "https://github.com/DopplerHQ/kubernetes-operator/releases/latest/download/recommended.yaml", server reported 404 Not Found, status code=404

**Comment by nmanoogian** [comment]
Thanks for reporting this @pve and sorry for the trouble. We're on it.

**Comment by nmanoogian** [comment]
We've fixed our build job and released a new version, which should solve the problem. Thanks again for letting us know and please let me know if you have any trouble installing [v1.2.5](https://github.com/DopplerHQ/kubernetes-operator/releases/tag/v1.2.5)!

**Comment by pve** [comment]
Looks like the file is there. Will check my ArgoCD setup tomorrow. 
Happy to see my second issues with doppler resolved :-).
